### ISSUE TITLE
Provide option to change piece size

### ISSUE THREAD

**Issue by Krzmbrzl** [samcarter/jigsaw#2]
As far as I can tell there is currently no way to change a piece's size. It'll always be 1x1. Changing the piece's size would be very handy though, if you want to add text into it.

I tried using `\piece[scale=3]{1}{1}{1}{1}` but this will only scale the filled-in background but not the piece's outline. In this context, maybe it would make sense to replace
https://github.com/samcarter/jigsaw/blob/566a47aa308f05c2b1680d27eb958789668a2a5a/jigsaw.sty#L46-L62
with something along the lines of
```latex
\newcommand{\piece}[5][\@nil]{
\edef\fillCmd{
% sudo-code - use an expandable if here
if #1 == \@nil then "fill=#1" else ""
}
  \path[draw, \filler, <potentially other user-supplied options>,]
    \side{#2}
    [rotate around={90:(0.5,0.5)}] -- \side{#3}
    [rotate around={90:(0.5,0.5)}] -- \side{#4}
    [rotate around={90:(0.5,0.5)}] -- \side{#5};    
}
```
That would change the interface a bit, but imo would allow for a more flexible use.

----

As a workaround for changing the size, it is also possible to wrap the entire piece into a `scope` and set the `scale` option on that. But this becomes a bit tedious once one has to organize multiple pieces.

**Comment by samcarter** [comment]
The optional argument of `\piece` is only meant to change the colour. If you need access to TikZ options like scale, you could use the pieces as a `pic`, e.g.:

```
\documentclass{article}
\usepackage{jigsaw}

\begin{document}
	
\begin{tikzpicture}
      \path pic[
         scale=5,
         fill=lightgray,
         draw=teal
       ]{piece={1}{-1}{1}{0}};
\end{tikzpicture}
	
     
\end{document}
```

![test](https://user-images.githubusercontent.com/43832342/219661984-6895d262-b91d-4a99-bc9d-aa79dfa500a5.png)

(I'm aware of the problem with the line-joins when scaling the piece - edit: I just submitted a fix)

**Comment by samcarter** [comment]
I just made some modifications to make it easier to add text to the pic  https://github.com/samcarter/jigsaw/commit/8483dbdf6415c4e88e3f3552359e857be32ce510

<img width="622" alt="Screenshot 2023-02-17 at 15 59 44" src="https://user-images.githubusercontent.com/43832342/219689750-712809ca-e1fb-4302-a8c8-b884ff801c51.png">

**Comment by Krzmbrzl** [comment]
Cool, thanks :+1:

**Comment by samcarter** [comment]
@Krzmbrzl  You're welcome! Have fun with the puzzle pieces :)
