### ISSUE TITLE
Potential typo

### ISSUE THREAD

**Issue by Krzmbrzl** [samcarter/jigsaw#3]
https://github.com/samcarter/jigsaw/blob/566a47aa308f05c2b1680d27eb958789668a2a5a/jigsaw.sty#L48
Shouldn't this be `\@nil` (only one `n`)? At least that's what the default arg seems to be set to :eyes:

**Comment by samcarter** [comment]
Thanks for the report, but this was working as intended. I took the opportunity to replace the code with a simpler approach using `\IfValueT`
